#!/usr/bin/env node
/**
 * AIMess Scenario Validation Framework — deterministic CI gate (Layer 2).
 *
 * Loads tools/scenario-validator/{rules,registry}.json, checks every business
 * action's declared side-effects against GROUND-TRUTH source evidence (regex
 * over the working tree), applies the rule engine, scores risk, writes
 * docs/SCENARIO_VALIDATION_REPORT.md + scenario-validation.json, and exits
 * non-zero when an action at/above the CI risk threshold is FAILED.
 *
 * Zero runtime deps. Node >= 18, ESM. Run: `node tools/scenario-validator/validate.mjs`
 * or `pnpm validate:scenarios`. Pair with the LLM `scenario-validator` agent
 * (Layer 1) which discovers actions MISSING from the registry.
 */
import { readFileSync, writeFileSync, existsSync, statSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = resolve(fileURLToPath(import.meta.url), "..");
const ROOT = resolve(HERE, "..", "..");
const rules = JSON.parse(readFileSync(join(HERE, "rules.json"), "utf8"));
const registry = JSON.parse(readFileSync(join(HERE, "registry.json"), "utf8"));

const PASS = "PASS", FAIL = "FAIL", WAIVED = "WAIVED", MISSING = "MISSING", NA = "n/a";
const ICON = { [PASS]: "✅", [FAIL]: "❌", [WAIVED]: "➖", [MISSING]: "❌", [NA]: "·" };
const RISK_RANK = { LOW: 1, MEDIUM: 2, HIGH: 3 };

// ---------- ground-truth evidence detection ----------
const fileCache = new Map();
function read(abs) {
  if (!fileCache.has(abs)) fileCache.set(abs, readFileSync(abs, "utf8"));
  return fileCache.get(abs);
}
function walkSrc(dir, acc = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (["node_modules", "dist", "generated", ".turbo"].includes(e.name)) continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) walkSrc(p, acc);
    else if (e.name.endsWith(".ts") || e.name.endsWith(".proto") || e.name.endsWith(".js")) acc.push(p);
  }
  return acc;
}
function evidenceFound(ev) {
  let re;
  try { re = new RegExp(ev.pattern); } catch { return false; }
  const targets = [];
  for (const f of ev.files ?? []) {
    const a = join(ROOT, f);
    if (existsSync(a) && statSync(a).isFile()) targets.push(a);
  }
  if (ev.dir) {
    const d = join(ROOT, ev.dir);
    if (existsSync(d) && statSync(d).isDirectory()) targets.push(...walkSrc(d));
  }
  return targets.some((a) => re.test(read(a)));
}

// ---------- rule engine ----------
function evaluate(action) {
  const rs = rules.rulesets[action.ruleSet];
  if (!rs) throw new Error(`Unknown ruleSet "${action.ruleSet}" on ${action.id}`);
  const required = new Set(rs.required);
  const recommended = new Set(rs.recommended ?? []);
  const keys = new Set([...required, ...recommended, ...Object.keys(action.effects ?? {})]);
  const results = {};
  const missing = [];
  let failedRequired = false, missingRecommended = false;
  for (const k of keys) {
    const decl = (action.effects ?? {})[k];
    let status;
    if (decl?.waived) status = WAIVED;
    else if (decl?.evidence) status = evidenceFound(decl.evidence) ? PASS : FAIL;
    else if (required.has(k) || recommended.has(k)) status = MISSING; // rule wants it, contract didn't declare it
    else status = NA;
    results[k] = status;
    const bad = status === FAIL || status === MISSING;
    if (required.has(k) && bad) { failedRequired = true; missing.push(k); }
    else if (recommended.has(k) && bad) { missingRecommended = true; missing.push(k); }
  }
  let overall, risk;
  if (failedRequired) { overall = "FAILED"; risk = action.riskOverride ?? rs.riskOnMissingRequired; }
  else if (missingRecommended) { overall = "WARN"; risk = action.riskOverride ?? rs.riskOnMissingRecommended ?? "LOW"; }
  else { overall = "PASS"; risk = "—"; }
  return { results, overall, risk, missing, ruleset: rs };
}

// ---------- run ----------
const evaluated = registry.actions.map((a) => ({ action: a, ...evaluate(a) }));
const failAt = RISK_RANK[rules.ciGate.failAtRisk] ?? 3;
const gateFailures = evaluated.filter(
  (e) => e.overall === "FAILED" && (RISK_RANK[e.risk] ?? 0) >= failAt
);

// ---------- report ----------
const order = rules.effectOrder;
const labels = rules.effectLabels;
const generatedAt = new Date().toISOString();
const counts = { PASS: 0, WARN: 0, FAILED: 0 };
for (const e of evaluated) counts[e.overall]++;
const riskCount = { HIGH: 0, MEDIUM: 0, LOW: 0 };
for (const e of evaluated) if (e.overall !== "PASS" && riskCount[e.risk] != null) riskCount[e.risk]++;

function recommendation(e) {
  if (e.overall === "PASS") return "—";
  const miss = e.missing.map((k) => labels[k] ?? k).join(", ");
  return `${e.action.fix ?? ""}${miss ? `  (missing: ${miss})` : ""}`.trim();
}

let md = "";
md += `# SCENARIO VALIDATION REPORT\n\n`;
md += `> Auto-generated by \`tools/scenario-validator/validate.mjs\` (deterministic, ground-truth\n`;
md += `> evidence over the working tree). Pair with the LLM \`scenario-validator\` agent for\n`;
md += `> discovery of actions missing from the registry. **Do not edit by hand.**\n>\n`;
md += `> Generated: ${generatedAt}\n\n`;
md += `## Summary\n\n`;
md += `| Result | Count |\n|---|---|\n`;
md += `| ✅ PASS | ${counts.PASS} |\n| ⚠️ WARN | ${counts.WARN} |\n| ❌ FAILED | ${counts.FAILED} |\n`;
md += `| **Total actions** | ${evaluated.length} |\n\n`;
md += `Open risk (non-PASS): **HIGH ${riskCount.HIGH} · MEDIUM ${riskCount.MEDIUM} · LOW ${riskCount.LOW}**\n\n`;
md += `**CI gate (fail at ≥ ${rules.ciGate.failAtRisk}):** ${gateFailures.length === 0 ? "✅ PASS" : `❌ FAIL — ${gateFailures.length} blocking action(s): ${gateFailures.map((g) => g.action.id).join(", ")}`}\n\n`;
md += `Legend: ✅ wired · ❌ missing · ➖ waived (documented n/a) · · not applicable\n\n---\n\n`;

// group by domain
const byDomain = new Map();
for (const e of evaluated) {
  if (!byDomain.has(e.action.domain)) byDomain.set(e.action.domain, []);
  byDomain.get(e.action.domain).push(e);
}
for (const [domain, items] of byDomain) {
  md += `## ${domain}\n\n`;
  for (const e of items) {
    const badge = e.overall === "PASS" ? "✅ PASS" : e.overall === "WARN" ? "⚠️ WARN" : "❌ FAILED";
    md += `### ${e.action.title} — ${badge}${e.risk !== "—" ? `  ·  Risk: ${e.risk}` : ""}\n\n`;
    md += "```\n";
    md += `Feature: ${e.action.title}   [${e.action.id}]\n`;
    for (const k of order) {
      if (!(k in e.results)) continue;
      const s = e.results[k];
      md += `${ICON[s]} ${(labels[k] ?? k).padEnd(24)} ${s}\n`;
    }
    md += `Risk: ${e.risk}\n`;
    md += `Recommendation: ${recommendation(e)}\n`;
    md += "```\n\n";
    if (e.overall !== "PASS" && e.action.impact && e.action.impact !== "—") {
      md += `Impact: ${e.action.impact}\n\n`;
    }
  }
}

md += `---\n\n## Findings table\n\n`;
md += `| Feature | Status | Risk | Missing | Service |\n|---|---|---|---|---|\n`;
for (const e of evaluated) {
  const miss = e.missing.map((k) => labels[k] ?? k).join(", ") || "—";
  md += `| ${e.action.title} | ${e.overall} | ${e.risk} | ${miss} | ${e.action.service} |\n`;
}
md += `\n`;

const reportPath = join(ROOT, "docs", "SCENARIO_VALIDATION_REPORT.md");
writeFileSync(reportPath, md);
const json = {
  generatedAt,
  summary: counts,
  openRisk: riskCount,
  ciGate: { failAtRisk: rules.ciGate.failAtRisk, passed: gateFailures.length === 0, blocking: gateFailures.map((g) => g.action.id) },
  actions: evaluated.map((e) => ({ id: e.action.id, title: e.action.title, service: e.action.service, status: e.overall, risk: e.risk, effects: e.results, missing: e.missing })),
};
writeFileSync(join(ROOT, "docs", "scenario-validation.json"), JSON.stringify(json, null, 2));

// ---------- console ----------
console.log(`\nScenario Validation — ${evaluated.length} actions: ✅ ${counts.PASS}  ⚠️ ${counts.WARN}  ❌ ${counts.FAILED}`);
console.log(`Open risk: HIGH ${riskCount.HIGH} · MEDIUM ${riskCount.MEDIUM} · LOW ${riskCount.LOW}`);
for (const e of evaluated.filter((x) => x.overall !== "PASS")) {
  console.log(`  ${e.overall === "FAILED" ? "❌" : "⚠️ "} [${e.risk}] ${e.action.id} — missing: ${e.missing.join(", ") || "—"}`);
}
console.log(`\nReport: docs/SCENARIO_VALIDATION_REPORT.md  (+ docs/scenario-validation.json)`);
if (gateFailures.length > 0) {
  console.error(`\n❌ CI GATE FAILED: ${gateFailures.length} action(s) FAILED at risk ≥ ${rules.ciGate.failAtRisk}: ${gateFailures.map((g) => g.action.id).join(", ")}`);
  process.exit(1);
}
console.log(`\n✅ CI gate passed (no FAILED action at risk ≥ ${rules.ciGate.failAtRisk}).`);
