#!/usr/bin/env bash
# Firewall for Dev 01 (76.13.216.164) — data, messaging, storage, SFU, website.
#
#   sudo bash 01-firewall-dev01.sh
#
# ============================================================================
# WHY THIS SCRIPT HAS TWO HALVES
#
# Docker inserts its own iptables rules AHEAD of ufw's. A container that
# publishes a port is therefore reachable from the internet even when
# `ufw status` shows that port as denied — ufw never sees the packet.
#
# So:
#   • HOST services (nginx, sshd, LiveKit on network_mode:host) → ufw.
#   • CONTAINER published ports (Postgres, Mongo, RabbitMQ, MinIO) → rules in
#     the DOCKER-USER chain, which Docker evaluates FIRST and never flushes.
#
# Getting only the ufw half right leaves Postgres and MongoDB wide open on the
# public internet with just a password in front of them.
# ============================================================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: must run as root (use sudo)." >&2
  exit 1
fi

SSH_PORT=22223
WAN_IF=eth0
DEV02_IP=76.13.216.171
STREAM_IP=72.62.69.126

# Ports published by containers on the LAN interface, protected via DOCKER-USER.
#   5432  Postgres   27017 MongoDB   5672 RabbitMQ AMQP   9000 MinIO S3
PROTECTED_PORTS=5432,27017,5672,9000

echo "==> [1/3] ufw — host-level services"

# Allow SSH FIRST. Enabling ufw with a default-deny policy before this rule
# exists drops the very connection running this script.
ufw allow "${SSH_PORT}/tcp" comment 'SSH'

ufw default deny incoming
ufw default allow outgoing

# nginx — public TLS termination.
ufw allow 80/tcp  comment 'HTTP (ACME + redirect)'
ufw allow 443/tcp comment 'HTTPS'

# LiveKit runs with network_mode:host, so it binds host ports directly and ufw
# DOES apply to it (unlike the published container ports handled below).
#   7880  signaling WS (also fronted by nginx)
#   7881  RTC/TCP fallback for UDP-blocked clients
#   50000-50100/udp  media
# These must be open to the whole internet — participants connect from
# arbitrary addresses, so no source restriction is possible.
ufw allow 7881/tcp comment 'LiveKit RTC TCP fallback'
ufw allow 50000:50100/udp comment 'LiveKit media (UDP)'

ufw --force enable
echo "    ufw enabled."

echo "==> [2/3] installing DOCKER-USER rule set"

cat > /usr/local/sbin/aimess-docker-firewall.sh <<EOF
#!/usr/bin/env bash
# GENERATED by deploy/scripts/01-firewall-dev01.sh — do not edit by hand.
#
# Restricts container-published database ports to known peers. Re-applied on
# every boot by aimess-docker-firewall.service, because iptables rules do not
# survive a reboot and Docker rebuilds its chains at startup.
set -euo pipefail

# DOCKER-USER only ever contains our rules plus Docker's trailing RETURN, so
# flushing it is safe and makes this script idempotent.
iptables -F DOCKER-USER

# Return traffic for connections we already accepted.
iptables -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN

# The application server may reach the datastores.
iptables -A DOCKER-USER -i ${WAN_IF} -p tcp -m multiport --dports ${PROTECTED_PORTS} -s ${DEV02_IP} -j RETURN

# Everything else arriving from the internet for those ports is dropped.
# DROP (not REJECT) so a scanner sees a timeout rather than a closed port.
iptables -A DOCKER-USER -i ${WAN_IF} -p tcp -m multiport --dports ${PROTECTED_PORTS} -j DROP

# Hand anything else back to Docker's own chains.
iptables -A DOCKER-USER -j RETURN
EOF

chmod 0755 /usr/local/sbin/aimess-docker-firewall.sh

cat > /etc/systemd/system/aimess-docker-firewall.service <<'EOF'
[Unit]
Description=AIMESS DOCKER-USER firewall rules
# Must run after Docker, which creates the DOCKER-USER chain at startup.
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/aimess-docker-firewall.sh

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now aimess-docker-firewall.service
echo "    DOCKER-USER rules applied and enabled at boot."

echo "==> [3/3] verification"
echo
echo "--- ufw ---"
ufw status verbose
echo
echo "--- DOCKER-USER ---"
iptables -L DOCKER-USER -n -v --line-numbers
echo
echo "Dev 01 firewall configured."
echo
echo "VERIFY FROM AN OUTSIDE MACHINE (all four MUST time out):"
echo "  nc -vz 76.13.216.164 5432"
echo "  nc -vz 76.13.216.164 27017"
echo "  nc -vz 76.13.216.164 5672"
echo "  nc -vz 76.13.216.164 9000"
echo "and FROM Dev 02 (all four MUST connect):"
echo "  for p in 5432 27017 5672 9000; do nc -vz 76.13.216.164 \$p; done"
echo
echo "NOTE: ${STREAM_IP} (stream server) needs no access to this host."
