#!/usr/bin/env bash
# Firewall for Dev 02 (76.13.216.171) â€” application services + admin panel.
#
#   sudo bash 02-firewall-dev02.sh
#
# See the long comment in 01-firewall-dev01.sh for why container ports need
# DOCKER-USER rules rather than ufw.
#
# Every service on this host publishes to 127.0.0.1 only, so nginx is the sole
# public path in and no container port is exposed off-box at all.
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: must run as root (use sudo)." >&2
  exit 1
fi

SSH_PORT=22223
WAN_IF=eth0

echo "==> [1/3] ufw â€” host-level services"

# Allow SSH FIRST â€” enabling default-deny before this drops this session.
ufw allow "${SSH_PORT}/tcp" comment 'SSH'

ufw default deny incoming
ufw default allow outgoing

ufw allow 80/tcp  comment 'HTTP (ACME + redirect)'
ufw allow 443/tcp comment 'HTTPS'

ufw --force enable
echo "    ufw enabled."

echo "==> [2/3] installing DOCKER-USER rule set"

cat > /usr/local/sbin/aimess-docker-firewall.sh <<EOF
#!/usr/bin/env bash
# GENERATED by deploy/scripts/02-firewall-dev02.sh â€” do not edit by hand.
#
# Default-deny for container traffic arriving from the internet. Re-applied on
# every boot by aimess-docker-firewall.service.
#
# Every service on this host publishes to 127.0.0.1 only, so nginx is the sole
# legitimate path in and NOTHING should reach a container directly from eth0.
# This is therefore a blanket drop rather than a per-port allowlist: if someone
# later adds a published port without thinking, it stays closed by default
# instead of silently appearing on the public internet.
#
# gRPC (4001-4010) is authenticated by GRPC_SERVICE_TOKEN but travels
# UNENCRYPTED, which is exactly why none of it is published off-box.
set -euo pipefail

iptables -F DOCKER-USER

# Return traffic for connections the host itself established (image pulls etc).
iptables -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN

# Anything else inbound from the internet to a container is dropped.
# DROP (not REJECT) so a scanner sees a timeout rather than a closed port.
iptables -A DOCKER-USER -i ${WAN_IF} -j DROP

iptables -A DOCKER-USER -j RETURN
EOF

chmod 0755 /usr/local/sbin/aimess-docker-firewall.sh

cat > /etc/systemd/system/aimess-docker-firewall.service <<'EOF'
[Unit]
Description=AIMESS DOCKER-USER firewall rules
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/aimess-docker-firewall.sh

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now aimess-docker-firewall.service
echo "    DOCKER-USER rules applied and enabled at boot."

echo "==> [3/3] verification"
echo
echo "--- ufw ---"
ufw status verbose
echo
echo "--- DOCKER-USER ---"
iptables -L DOCKER-USER -n -v --line-numbers
echo
echo "--- published ports (every container port must show 127.0.0.1) ---"
ss -tulnp | grep -E 'docker|LISTEN' | head -30
echo
echo "Dev 02 firewall configured."
echo
echo "VERIFY FROM AN OUTSIDE MACHINE — every one of these MUST time out,"
echo "because nginx is the only thing that should answer from outside:"
echo "  for p in 3000 3001 3004 3010 3011 4001 4002 4003 4004; do nc -vz -w3 76.13.216.171 \$p; done"
