#!/usr/bin/env bash
# Firewall for Dev 02 (76.13.216.171) — application services + admin panel.
#
#   sudo bash 02-firewall-dev02.sh
#
# See the long comment in 01-firewall-dev01.sh for why container ports need
# DOCKER-USER rules rather than ufw.
#
# On this host almost every service publishes to 127.0.0.1 only, so nginx is
# the sole public path in. The two exceptions are the user-service and
# community-service gRPC ports, which the remote stream-service must reach.
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: must run as root (use sudo)." >&2
  exit 1
fi

SSH_PORT=22223
WAN_IF=eth0
STREAM_IP=72.62.69.126

# 4002 user-service gRPC, 4003 community-service gRPC — needed by the remote
# stream-service only.
PROTECTED_PORTS=4002,4003

echo "==> [1/3] ufw — host-level services"

# Allow SSH FIRST — enabling default-deny before this drops this session.
ufw allow "${SSH_PORT}/tcp" comment 'SSH'

ufw default deny incoming
ufw default allow outgoing

ufw allow 80/tcp  comment 'HTTP (ACME + redirect)'
ufw allow 443/tcp comment 'HTTPS'

ufw --force enable
echo "    ufw enabled."

echo "==> [2/3] installing DOCKER-USER rule set"

cat > /usr/local/sbin/aimess-docker-firewall.sh <<EOF
#!/usr/bin/env bash
# GENERATED by deploy/scripts/02-firewall-dev02.sh — do not edit by hand.
#
# Restricts the two published gRPC ports to the stream server. Re-applied on
# every boot by aimess-docker-firewall.service.
#
# gRPC here is authenticated by GRPC_SERVICE_TOKEN but travels UNENCRYPTED, so
# the source restriction is the only thing keeping it off the open internet.
set -euo pipefail

iptables -F DOCKER-USER

iptables -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN

# The stream server may call user-service and community-service over gRPC.
iptables -A DOCKER-USER -i ${WAN_IF} -p tcp -m multiport --dports ${PROTECTED_PORTS} -s ${STREAM_IP} -j RETURN

# Everything else from the internet for those ports is dropped.
iptables -A DOCKER-USER -i ${WAN_IF} -p tcp -m multiport --dports ${PROTECTED_PORTS} -j DROP

iptables -A DOCKER-USER -j RETURN
EOF

chmod 0755 /usr/local/sbin/aimess-docker-firewall.sh

cat > /etc/systemd/system/aimess-docker-firewall.service <<'EOF'
[Unit]
Description=AIMESS DOCKER-USER firewall rules
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/aimess-docker-firewall.sh

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now aimess-docker-firewall.service
echo "    DOCKER-USER rules applied and enabled at boot."

echo "==> [3/3] verification"
echo
echo "--- ufw ---"
ufw status verbose
echo
echo "--- DOCKER-USER ---"
iptables -L DOCKER-USER -n -v --line-numbers
echo
echo "--- published ports (everything except 4002/4003 must show 127.0.0.1) ---"
ss -tulnp | grep -E 'docker|LISTEN' | head -30
echo
echo "Dev 02 firewall configured."
echo
echo "VERIFY FROM AN OUTSIDE MACHINE (both MUST time out):"
echo "  nc -vz 76.13.216.171 4002"
echo "  nc -vz 76.13.216.171 4003"
echo "and that the app ports are NOT publicly bound (all MUST time out):"
echo "  for p in 3000 3004 3010 3011; do nc -vz 76.13.216.171 \$p; done"
