#!/usr/bin/env bash
# Regenerate /etc/nginx/snippets/aimess-cloudflare-realip.conf from Cloudflare's
# published edge ranges.
#
#   sudo bash refresh-cloudflare-ips.sh
#
# WHY THIS MATTERS
# Requests arrive from Cloudflare's edge, so without this every request appears
# to originate from a Cloudflare IP. Three things break as a result:
#   • Rate limiting keys on the proxy IP, so one abusive client throttles all.
#   • ADMIN_IP_WHITELIST and any nginx allow/deny match the wrong address.
#   • Audit logs record a Cloudflare IP instead of the actual admin.
#
# Cloudflare adds ranges occasionally. Re-run this after any such change —
# a missing range means those clients silently fall back to the proxy IP.
set -euo pipefail

OUT=/etc/nginx/snippets/aimess-cloudflare-realip.conf
TMP=$(mktemp)

{
  echo "# GENERATED by deploy/scripts/refresh-cloudflare-ips.sh — do not edit by hand."
  echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo

  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    # --fail so an HTML error page never gets written in as a CIDR.
    curl -fsSL "$url" | while read -r cidr; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done
  done

  echo
  echo "# Trust CF-Connecting-IP, which Cloudflare sets to the true client address."
  echo "# Unlike X-Forwarded-For it is a single value the edge always overwrites,"
  echo "# so a client cannot spoof it by sending their own header."
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

# A truncated download would silently disable real-IP handling and, combined
# with an allow/deny list, lock everyone out. Refuse to install a short file.
if [ "$(grep -c set_real_ip_from "$TMP")" -lt 10 ]; then
  echo "ERROR: only $(grep -c set_real_ip_from "$TMP") ranges fetched — refusing to install." >&2
  rm -f "$TMP"
  exit 1
fi

install -m 0644 "$TMP" "$OUT"
rm -f "$TMP"
echo "Wrote $OUT ($(grep -c set_real_ip_from "$OUT") ranges)"

nginx -t && systemctl reload nginx
echo "nginx reloaded."
